config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get "/about", to: "pages#about", as: :about
  get "/snippets", to: "snippets#index", as: :snippets

  get "/snippets/custom-redirect-devise", to: "snippets#custom"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def snippets
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def index
  end

  def custom
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pbragamiranda</title>
    <%= favicon_link_tag asset_path('botafogo.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="min-h-screen">
      <%= render 'shared/navbar' %>
      <%= render 'shared/wave'  %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/_about.html.erb
<section id="about-me">
  <%= render(SectionHeadingComponent.new(title: "About Me")) %>

  <div class="about">
    <div>
      <p>
        Hello! My name is Brittany and I enjoy creating things that live on the internet.
        My interest in web development started back in 2012 when I decided to try editing custom Tumblr themes
      </p>
      <p>
        — turns out hacking together a custom reblog button taught me a lot about HTML & CSS!
        Fast-forward to today, and I’ve had the privilege of working at an advertising agency, a start-up, a huge corporation,
        and a student-led design studio. My main focus these days is building accessible, inclusive products and digital experiences at Upstatement for a variety of clients.
      </p>
      <p>
        I also recently launched a course that covers everything you need to build a web app with
        the Spotify API using Node & React.
        Here are a few technologies I’ve been working with recently:
      </p>
    </div>

    <div class=photo>
      <%= image_tag "profile.png" %>
      <span class="box"></span>
    </div>

  </div>
</section>

app/views/pages/_connect.html.erb
<section id="connect">
  <%= render(SectionHeadingComponent.new(title: "Get in Touch")) %>
  <p style="font-size: 20px;">
    I’m interested in freelance opportunities.
    If you have other request or question, don’t hesitate to <span style="color: #10b981"><%= mail_to "pbragamiranda@pm.me", "contact me" %></span>.
  </p>
</section>

app/views/pages/_intro.html.erb
<section>
  <ul class="social flex items-center">
    <li>
      <span class="social-line"></span>
    </li>
    <li>
      <%= mail_to "pbragamiranda@pm.me" do  %>
        <i class="fa-regular fa-envelope"></i>
      <% end %>
    </li>
    <li>
      <%= link_to "https://www.linkedin.com/in/pbragamiranda/" do  %>
        <i class="fa-brands fa-linkedin-in"></i>
      <% end %>
    </li>
    <li>
      <%= link_to "https://github.com/pbragamiranda" do  %>
        <i class="fa-brands fa-github"></i>
      <% end %>
    </li>
    <li>
      <%= link_to "https://twitter.com/pbragamiranda" do  %>
        <i class="fa-brands fa-twitter"></i>
      <% end %>
    </li>
  </ul>

  <div class="intro flex-col">
    <p>colé,</p>
    <h1>I'm pedro.</h1>
    <h2>Full Stack Developer & Teacher.</h2>
    <h5>I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences.
        Currently, I’m focused on building accessible, human-centered products at</h5>
  </div>

</section>

app/views/pages/_projects.html.erb
<section id="projects">
  <%= render(SectionHeadingComponent.new(title: "Projects")) %>

  <div class="flex justify-between">
    <p>https://pbragamiranda.github.io/pbragamiranda/</p>
  </div>
</section>

app/views/pages/_skills.html.erb
<section id="skills">
  <%= render(SectionHeadingComponent.new(title: "Development Background")) %>
  <div class="flex-col">
    <div>
      <h3>I'm a fan and mainly code in <strong>Ruby</strong>, <strong>Ruby on Rails</strong>, and <strong>JavaScript</strong>. I also enjoy the <strong>Hotwire</strong> approach and like to use <strong>Stimulus</strong> and <strong>Turbo</strong>.</h3>
      <h3>In the front-end, I've been using <strong>TailwindCSS</strong> and <strong>ViewComponents</strong> more and more, but I'm also used to <strong>CSS</strong>, <strong>SCSS</strong>, and <strong>Bootstrap</strong>.</h3>
      <h3>It's been a while since I've worked with data, but I have coded quite a bit with <strong>Python</strong>, <strong>Pandas</strong>, and <strong>NumPy</strong>.</h3>
      <div class="flex mt-4">
        <!-- git -->
        <a href="https://git-scm.com/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" alt="git" width="40" height="40"/>
        <!-- ruby  -->
        <a href="https://www.ruby-lang.org/en/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/ruby/ruby-original.svg" alt="ruby" width="40" height="40"/> </a>
        <!-- rails -->
        <a href="https://rubyonrails.org" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/rails/rails-original-wordmark.svg" alt="rails" width="40" height="40"/> </a>
        <!-- js -->
        <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="javascript" width="40" height="40"/> </a>
        <!--postgresql  -->
        <a href="https://www.postgresql.org" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg" alt="postgresql" width="40" height="40"/> </a>
        <!-- tailwind -->
        <a href="https://tailwindcss.com/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg" alt="tailwind" width="40" height="40"/> </a>
        <!-- sccs  -->
        <a href="https://sass-lang.com" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg" alt="sass" width="40" height="40"/> </a>
        <!-- html -->
        <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/> </a>
        <!-- css -->
        <a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="40" height="40"/> </a>
        <!-- heroku -->
        <a href="https://heroku.com" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg" alt="heroku" width="40" height="40"/> </a>
        <!-- python -->
        <a href="https://www.python.org" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" alt="python" width="40" height="40"/> </a>
        <!-- pandas -->
        <a href="https://pandas.pydata.org/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/2ae2a900d2f041da66e950e4d48052658d850630/icons/pandas/pandas-original.svg" alt="pandas" width="40" height="40"/> </a>
      </div>
    </div>
    <div class="mt-8">
      <h3>I'm currently learning <strong>Node.js</strong>, <strong>Express.js</strong>, <strong>GraphQL</strong> and <strong>Docker</strong>.</h3>
      <div class="flex mt-4">
        <!-- node.js -->
        <a href="https://nodejs.org" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg" alt="nodejs" width="40" height="40"/> </a>
        <!-- express.js -->
        <a href="https://expressjs.com" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg" alt="express" width="40" height="40"/> </a>
        <!-- graphql -->
        <a href="https://graphql.org" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/graphql/graphql-icon.svg" alt="graphql" width="40" height="40"/> </a>
        <!-- docker -->
        <a href="https://www.docker.com/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg" alt="docker" width="40" height="40"/> </a>
      </div>
    </div>
  </div>
</section>

app/views/pages/_work.html.erb
<section id="work-experience">
  <%= render(SectionHeadingComponent.new(title: "Work Experience")) %>

  <div class= "work" data-controller="tabs" data-tabs-default-tab-value="one">

    <div class="work-tabs">
      <button id="one" data-tabs-target="btn" data-action="click->tabs#select">&ensp; Le Wagon  &ensp;</button>
      <button id="two" data-tabs-target="btn" data-action="click->tabs#select">&ensp; ChartMogul &ensp;</button>
      <button id="three" data-tabs-target="btn" data-action="click->tabs#select">&ensp; Telos Lab &ensp;</button>
      <button id="four" data-tabs-target="btn" data-action="click->tabs#select">&ensp; FGV / EBAPE &ensp;</button>
      <button id="five" data-tabs-target="btn" data-action="click->tabs#select">&ensp; Public Sector &ensp;</button>
    </div>

    <div>
      <div data-tabs-target="tab" id="one">
        <%= render(WorkExperienceComponent.new(company: "Le Wagon", position: "Web Dev Teacher & Batch Manager", duration: "Oct 2020 - Present", url: "https://www.lewagon.com/")) do %>
          Teaching technical skills to creative people.
          <br>
          <br>

          Presenting lectures and workshops about Ruby, HTML, CSS, JavaScript, Ruby on Rails , relational databases (SQLite and PostgreSQL) and MVC architecture.
          Assisting students in 1 on 1 fashion.
          Contributing & creating solutions for students final projects
        <% end %>
      </div>
      <div data-tabs-target="tab" id="two">
        <%= render(WorkExperienceComponent.new(company: "ChartMogul", position: "Backend Engineer", duration: "Jan 2023 - Feb 2023", url: "https://chartmogul.com/")) do %>
          Integrations team
        <% end %>
      </div>
      <div data-tabs-target="tab" id="three">
        <%= render(WorkExperienceComponent.new(company: "Telos Lab", position: "Full Stack Developer", duration: "Sep 2021 - Jul 2022", url: "https://www.teloslabs.co/")) do %>
          Creating digital products and strategies for social impact.

          * Designing, development, and maintaining of Web-Applications with Ruby on Rails.
          * Full Stack Developer, mainly focused on back-end solutions.
          * Frequently communicating with clients.
        <% end %>
      </div>
      <div data-tabs-target="tab" id="four">
        <%= render(WorkExperienceComponent.new(company: "FGV / EBAPE", position: "Monitor", duration: "Jun 2020 - Dec 2020", url: "https://ebape.fgv.br/")) do %>
          Descriptive Statistics with Python monitor for FGV's undergraduate students.

          * Translated code from R to Python
          * Weekly office hours to clear students doubts
        <% end %>
      </div>
      <div data-tabs-target="tab" id="five">
        <%= render(WorkExperienceComponent.new(company: "Public Sector", position: "Various", duration: "Jun 2020 - Dec 2020", url: "#")) do %>
          Descriptive Statistics with Python monitor for FGV's undergraduate students.

          * Translated code from R to Python
          * Weekly office hours to clear students doubts
        <% end %>
      </div>
    </div>

  </div>
</section>

app/views/pages/about.html.erb
<div class="container mx-auto flex flex-col justify-center items-center">
  <%= render 'about'  %>
  <%= render 'skills' %>
  <%= render 'work'  %>
</div>

app/views/pages/home.html.erb
<div class="container mx-auto flex flex-col justify-center items-center">
  <%= render 'intro' %>
  <%= render 'about'  %>
  <%= render 'skills' %>
  <%= render 'work'  %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer sticky top-[100vh]">
  <div class="content">
    - Coded with Ruby on Rails, HotWire, and Tailwind CSS by Me <i class="fas fa-coffee"></i>
  </div>
</footer>

app/views/shared/_left.html.erb
<ul class="left flex flex-col items-center">
  <li>
    <%= link_to "https://github.com/pbragamiranda" do  %>
      <i class="fa-brands fa-github"></i>
    <% end %>
  </li>
  <li>
    <%= link_to "https://www.linkedin.com/in/pbragamiranda/" do  %>
      <i class="fa-brands fa-linkedin-in"></i>
    <% end %>
  </li>
  <li>
    <%= link_to "https://twitter.com/pbragamiranda" do  %>
      <i class="fa-brands fa-twitter"></i>
    <% end %>
  </li>
  <li>
    <%= mail_to "pbragamiranda@pm.me" do  %>
      <i class="fa-regular fa-envelope"></i>
    <% end %>
  </li>
  <span class="line"></span>
</ul>

app/views/shared/_navbar.html.erb
<nav>
  <div class="flex h-16 items-center justify-between my-8">
    <div class="flex items-center logo">
      <%= link_to root_path do %>
        <h1 class="mr-2">pedro miranda</h1>
      <% end %>
      <%= image_tag "botafogo.png", style: "height: 24px" %>
    </div>

    <div class="hidden sm:ml-6 sm:block nav">
      <div class="flex space-x-4">
        <%= link_to about_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" do %>
          About Me</a>
        <% end %>
        <a href="#projects" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">
          Projects</a>
        <%= link_to snippets_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" do %>
          Code Snippets</a>
          <% end %>
        <a href="#work-experience" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">
          Notes</a>
        <a href="#work-experience" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">
          Get in Touch</a>
        <i class="fa-solid fa-language"></i>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_right.html.erb
<ul class="right flex flex-col items-center">
  <a href="mailto:pbragamiranda@pm.me">pbragamiranda@pm.me</a>
  <div class="line"></div>
</ul>

app/views/shared/_wave.html.erb
<div class="wave">
    <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M649.97 0L599.91 54.12 550.03 0 0 0 0 120 1200 120 1200 0 649.97 0z" class="shape-fill"></path>
    </svg>
</div>

app/views/snippets/custom.html.erb
<section>
  <div class="title">
    <h1>Custom Redirect for Devise</h1>
    <p>#tutorial #rails #devise</p>
  </div>
</section>

app/views/snippets/index.html.erb
<section>
  <div class="title">
    <h1>Some Code Snippets and Quick Tutorials</h1>
    <p>
      Short #tutorials and some code #snippets
    </p>
  </div>

  <div class="relative rounded-xl overflow-auto mt-8">
    <div class="shadow-sm overflow-hidden my-8">
      <table class="border-collapse table-auto w-full text-sm">
        <thead>
          <tr>
            <th class="border-b dark:border-slate-600 font-medium p-4 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">Name</th>
            <th class="border-b dark:border-slate-600 font-medium p-4 pl-8 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">Description</th>
            <th class="border-b dark:border-slate-600 font-medium p-4 pr-8 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">Category</th>
            <th class="border-b dark:border-slate-600 font-medium p-4 pr-8 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">Last Updated</th>
          </tr>
        </thead>
        <tbody class="bg-white dark:bg-slate-800">
          <%= render SnippetRowComponent.new(url: "#", name: "Custom Redirect Devise",
                                             description:"Create a custom redirect after sign in / log in when using Devise gem",
                                             category: "Ruby on Rails", last_updated: "Mar 2023") %>
          <%= render SnippetRowComponent.new(url: :snippets_custom_redirect_devise,name: "Tabs with StimulusJS",
                                             description:"Create Tabs with StimulusJS",
                                             category: "JavaScript", last_updated: "Mar 2023") %>
          <%= render SnippetRowComponent.new(url: "#", name: "Tags with TagifyJS",
                                             description:"Create tags with TagifyJS",
                                             category: "JavaScript", last_updated: "Feb 2023") %>
        </tbody>
      </table>
    </div>
  </div>
</section>